version: '3'

services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: coffee
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: Ivaska
      MYSQL_PASSWORD: password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  coffee-app:
    restart: on-failure
    build: ./
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/coffee?allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
      - docker-mysql