# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: coffee
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: Ivaska
          MYSQL_PASSWORD: password
        volumes:
          - ./sql:/docker-entrypoint-initdb.d
        ports:
          - "3307:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v1
#      - run: mysql -h 127.0.0.1 --port 3306 -u Ivaska -ppassword -e 'CREATE DATABASE IF NOT EXISTS coffee;'
      - name: Build with Maven
        run: mvn clean install